"""Render a stored incident as a Markdown report (plain text; render it safely if you show it as HTML)."""
from app.enrich.mitre import lookup_mitre


def _bullets(items) -> str:
    return "\n".join(f"- {i}" for i in items) or "- (none)"


def incident_markdown(d: dict) -> str:
    inc, alert = d["incident"], d["alert"]
    L = [f"# Incident #{d['id']}: {inc['title']}", "",
         "| Field | Value |", "|---|---|",
         f"| Severity | **{inc['severity']}** |",
         f"| Verdict | {inc['verdict']} (confidence: {inc['confidence']}) |",
         f"| Status | {d['status']} |",
         f"| Source IP | {alert.get('src_ip') or '-'} |",
         f"| Detector | {alert.get('detector', '-')} (rule score {alert.get('score', '-')}) |",
         f"| First / last seen | {alert.get('first_seen', '-')} / {alert.get('last_seen', '-')} (UTC) |",
         f"| Events in pattern | {alert.get('count', '-')} |",
         f"| Created | {d['created_at']} |", ""]
    if d["fallback"]:
        L += ["> **The automated investigation did not complete. This is the rule-based alert only; "
              "a human must review it.**", ""]
    L += ["## Summary", inc["summary"], "", "## Evidence", _bullets(inc["evidence"]), "",
          "## MITRE ATT&CK", "| ID | Technique | Tactic |", "|---|---|---|"]
    for tid in inc["mitre"]:
        m = lookup_mitre(tid)
        L.append(f"| {tid} | {m.name if m else '-'} | {m.tactic if m else '-'} |")
    L += ["", "## Recommended actions (for a human to carry out)"]
    L += [f"{n}. [ ] {a}" for n, a in enumerate(inc["recommended_actions"], 1)] or ["- (none)"]
    L += ["", "## Reasoning", inc["reasoning"] or "-", ""]
    if inc["guardrail_notes"]:
        L += ["## Guardrail notes", _bullets(inc["guardrail_notes"]), ""]
    L += ["## Why the rules fired", _bullets(alert.get("score_reasons", [])), "",
          "## Raw log evidence", "```", *alert.get("evidence", []), "```", "",
          "## Investigation trail", f"Model: {d['model']} | rounds: {d['rounds']} | tokens: {d['tokens']}", ""]
    L += [f"{n}. `{t['tool']}` {t['arguments']}" for n, t in enumerate(d["tool_calls"], 1)] or ["- (no tool calls)"]
    if d["feedback"]:
        L += ["", "## Analyst feedback", _bullets(f"{f['label']}: {f['note']}" for f in d["feedback"])]
    L += ["", "---", "*Generated by Emissary. AI-assisted; every finding and action must be verified by a human analyst.*", ""]
    return "\n".join(L)
